name: Trigger Plugins Update (Encrypted)

on:
  push:
    branches:
      - main

jobs:
  notify-manager:
    runs-on: ubuntu-latest
    steps:
      - name: Send update webhook
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}
        run: |
          if [ -z "$SERVER_HOST" ] || [ -z "$SERVER_PORT" ] || [ -z "$SECRET_TOKEN" ]; then
            echo "SERVER_HOST, SERVER_PORT, and SECRET_TOKEN secrets must be set" >&2
            exit 1
          fi
          curl -sSf -X POST \
            -H "X-Secret-Token: ${SECRET_TOKEN}" \
            "http://${SERVER_HOST}:${SERVER_PORT}/update"
